import { Container } from "@chakra-ui/react";
import Head from "next/head";
import { ReactNode } from "react";

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Skip Router SDK Frontend Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container py={8}>{children}</Container>
    </>
  );
};
